# Generated by Django 2.0.2 on 2020-09-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporters',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], max_length=8, verbose_name='性别'),
        ),
    ]
