# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-02 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0002_auto_20200904_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporters',
            name='personal_webinfo',
            field=models.URLField(blank=True, verbose_name='网址个人博客等等'),
        ),
        migrations.AlterField(
            model_name='reporters',
            name='teacher_image',
            field=models.ImageField(upload_to='teacher/%Y/%m', verbose_name='老师的照片'),
        ),
        migrations.AlterField(
            model_name='reporters',
            name='title',
            field=models.CharField(max_length=50, verbose_name='学术报告人的简介'),
        ),
        migrations.AlterField(
            model_name='xueshuorg',
            name='org_desc',
            field=models.CharField(max_length=200, verbose_name='机构/大学学校描述'),
        ),
    ]
