# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-03 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0003_auto_20210302_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='xueshuorg',
            name='url',
            field=models.URLField(default='www.baidu.com', verbose_name='机构/大学学校网址'),
        ),
    ]
