# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-03 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0004_xueshuorg_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='xueshuorg',
            name='students',
            field=models.IntegerField(default=0, verbose_name='学习人数'),
        ),
    ]
