# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-01 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='xuehao',
            field=models.CharField(max_length=8, verbose_name='学号'),
        ),
    ]
