# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2020-09-03 16:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('download', models.FileField(max_length=200, upload_to='Xueshu/%Y/%m', verbose_name='资源文件')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学术资源',
                'verbose_name_plural': '学术资源',
            },
        ),
        migrations.CreateModel(
            name='Vedio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '直播回放视频',
                'verbose_name_plural': '直播回放视频',
            },
        ),
        migrations.CreateModel(
            name='Xueshu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('desc', models.CharField(max_length=200, verbose_name='描述')),
                ('url', models.URLField(verbose_name='官网的展示网页')),
                ('category', models.CharField(choices=[('A', '政治'), ('B', '文化'), ('C', '经济'), ('D', '军事'), ('E', '法律'), ('F', '科学'), ('G', '体育'), ('H', '历史'), ('I', '计算机'), ('J', '生物'), ('K', '历史'), ('L', '农业'), ('M', '工业'), ('N', '卫生'), ('O', '综合'), ('P', '艺术')], max_length=2, verbose_name='种类')),
                ('learn_time', models.IntegerField(default=150, verbose_name='举办时长/分钟')),
                ('hold_place', models.CharField(default='绵阳学术报告厅', max_length=50, verbose_name='举办地点')),
                ('student', models.IntegerField(default=0, verbose_name='报名人数')),
                ('fav_id', models.IntegerField(default=0, verbose_name='收藏数')),
                ('click_num', models.IntegerField(default=0, verbose_name='点击数')),
                ('image', models.ImageField(default='image/default.png', upload_to='xueshu/%Y/%m')),
                ('add_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '学术信息',
                'verbose_name_plural': '学术信息',
            },
        ),
        migrations.AddField(
            model_name='vedio',
            name='Xueshu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.Xueshu', verbose_name='学术报告'),
        ),
        migrations.AddField(
            model_name='resource',
            name='Xueshu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.Xueshu', verbose_name='学术报告'),
        ),
    ]
