# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-04 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Organization', '0005_xueshuorg_students'),
        ('Academic', '0002_vedio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='xueshu',
            name='Xueshu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Organization.XueshuOrg', verbose_name='学术机构'),
        ),
    ]
