# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-04 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0003_xueshu_xueshu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xueshu',
            old_name='Xueshu',
            new_name='xueshu_org',
        ),
    ]
