# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2021-03-04 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0004_auto_20210304_1409'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xueshu',
            old_name='xueshu_org',
            new_name='xueshu_orgs',
        ),
    ]
